function loginUser() {
    //clear any error messages
    $("#login-error").text();

    var email = $("#emailInput").val();
    var password = $("#passwordInput").val();

    firebase.auth().signInWithEmailAndPassword(email, password)
    .then(function() {
        console.log("user logged in successfully");

        refreshAccountNavigation();
        closeLoginForm();
    }
    ).catch(function(error) {
        //error handling
        console.log("failed signin, response:" + error);
        $("#login-error").text(error);
    });
}

function logoutUser() {
    firebase.auth().signOut().then(function() {
        console.log("Successfully signed out user");
        
        //go back to main page
        document.location='index.html';
    }, function(error) {
        alert(error.message);
    })
}

function checkForUserInDatabase(user) {
    var database = firebase.firestore();
    var docRef = database.collection("users").doc(user.uid)
    docRef.get().then(function(doc) {
        if (doc.exists) {
            //I'm assuming we will do more with this in the future
            console.log("User exists in database");
        } else {
            //If the user does not exist in the database we need to write them to it
            console.log("User not found in database");
            addUserToDatabase(user);
        }
    }).catch(function(error) {
       console.log("Error getting document ref: " + error); 
    });
}

function addUserToDatabase(user) {
    var database = firebase.firestore();
    
    // 1) All user entry document ids should be set to the user's uid that is generated by the auth
    // 2) I set username to the email, we should probably change the DB field to email instead since every user
    //    will have an email but not every user will have a display name
    database.collection("users").doc(user.uid).set({
        catalog: null,
        queue: null,
        username: user.email
    }).then(function() {
        console.log("User successfully written to database");
    }).catch(function(error) {
        console.log("Error writing user to database: " + error);
    });
}

function closeLoginForm() {
    //clear any error messages
    $("#login-error").text();

    $("#login-wrapper").addClass("hide");
    return false;
}